<?php

class MI_Order_Status
{
	//定单状态
	CONST ORDER_STATUS_DEFAULT = 0;//默认为未使用
	CONST ORDER_STATUS_NOUSER  = 0;//未使用
	CONST ORDER_STATUS_USER    = 1;//已使用
	CONST ORDER_STATUS_OVERTIME = 2;//已过期
	CONST ORDER_STATUS_UNDO    = 3; //已撤消

	//打印状态
	CONST ORDER_PRINT_STATUS_NO = 0;//未打印
	CONST ORDER_PRINT_STATUS_YES = 1;//已打印

	//付款状态
	CONST ORDER_PAY_STATUS_NO = 0;//未付款
	CONST ORDER_PAY_STATUS_YES = 1;//已付款

	//对帐状态
	CONST ORDER_DZ_STATUS_NO = 0;//未对账
	CONST ORDER_DZ_STATUS_YES = 1;//已对帐

	//出单状态
	CONST ORDER_BILLS_STATUS_NO = 0;//未出单
	CONST ORDER_BILLS_STATUS_YES = 1;//已出单

	//人工审核状态
	CONST ORDER_VERIFY_STATUS_NO = 0;//未审核
	CONST ORDER_VERIFY_STATUS_YES = 1;//已审核
	
	//支付来源(验证来源)
	CONST ORDER_PAY_SOURCE_WEB = 1;//web
	CONST ORDER_PAY_SOURCE_POS = 2;//pos

	//付款来源(付款方式)
	CONST ORDER_PAYMENT_SOURCE_CASH = 1;//现金
	CONST ORDER_PAYMENT_SOURCE_POS = 2;//pos
}
